### PR TITLE
Point updates for Astromechs and Illicit upgrades

### PR DESCRIPTION
**Pull request by acosoi**
Hello,

I've made some changes for Astromechs and Illicit upgrades, based on the data from the xwing-data2 repo.

This is my first time editing BattleScribe data, so I wanted to create a pull request just for this set of changes, to make sure I'm doing things right before I make any more corrections.

In addition to the changes detailed in the commit notes, I've also removed the cost of R5-TK (which now costs 0 points).

Thanks,
Andrei

### CODE REVIEW

**Comment by XWingDrLucky** [comment]
It sounds like you did everything right but I'll take a closer look tonight
and then merge it in.

Thanks for the help. Real life has been delaying me making all the Wave 4
updates but I'm ready to get back on it myself too (starting with the rest
of the ships).

**Comment by XWingDrLucky** [comment]
I see you experimented with the Modifier Group option.  I haven't played with it - I think it is a new option in one of the recent BattleScribe updates.  Does it just package a group of modifiers or does it do something more subtle?

**Comment by acosoi** [comment]
The BattleScribe patch notes say this:

> New Modifier Group element which can contain multiple Modifiers and Modifier Groups which are all applied together according to a single set of Conditions.

I was trying to use the group as a "folder" for multiple modifiers, in order to keep things tidy. Based on the notes, it appears that the intended use is to apply multiple different modifiers at once, based on a single condition, rather than having to set up multiple modifiers that have the exact same condition.

It wasn't how I using it, so I decided I should just remove it.

**Comment by XWingDrLucky** [comment]
Ahh, makes sense. I was hoping it might solve a problem I've had with other
repos (involving a single value being simultaneously the target of a Set
modifier and an Append modifier from different sources), but it appears
not.

**Pull request merged**
